### ISSUE TITLE
Large ducted fan node is flipped.

### ISSUE THREAD

**Issue by smjjames** [BobPalmer/FTT#101]
[s]Not exactly sure if the large ducted fans nodes are flipped or if it's the starlifter outrigger. pretty sure it's the outrigger.[/s]

It's the ducted fan which has a flipped node, tnanks to BigFatStupidHead on the forum for confirming for sure.
![screenshot99](https://cloud.githubusercontent.com/assets/11197436/8221649/cbbf8ef2-1515-11e5-9021-eb3a37aadac9.png)

**Comment by Kerbas-ad-astra** [comment]
RoverDude's accepted my pull request to fix it, so this should be fixed in the next version.
