### ISSUE TITLE
Starlifter large cargo rack nodes not working

### ISSUE THREAD

**Issue by asgkatz** [BobPalmer/FTT#102]
^. Can't attach large cargo rack to anything. Small works fine. Haven't checked with large rack as root part.

**Comment by mhoram-kerbin** [comment]
Can't be sure, but I believe #106 resolves this issue.

**Comment by henrybauer** [comment]
I tried with large rack as root part, doesn't work.

#106 does fix the end nodes, but the side nodes are still busted.  See #89 for the full fix (basically just also reverse the sign on node_stack_cargo_02, 04, and 06).

**Comment by BobPalmer** [comment]
Fixed in next release
