### ISSUE TITLE
Kontainer 15m refunds 718million

### ISSUE THREAD

**Issue by Prototype2001** [BobPalmer/FTT#120]
When crafting a 15m kontainer with karborundum the cost of launching the vessel is -718 million. To put that into perspective, the highest amount of currency i've had until i encountered this bug was around $600,000 on career hard, now im a billionare.

**Comment by dougiepowers** [comment]
I had the same Issue with a 2,5m container, not sure if it is an FTT bug or a stock bug. I could observe strange bahaviour with prebuilt crafts that I modified/changed parts for using them for another purpose. In my case the 2,5m container has a cost of -26K kerbucks. Here´s some pictures. In the bottom left you can see the cost of the craft before and after reattaching the container.
![kontainerafter](https://cloud.githubusercontent.com/assets/15268792/12946908/015221c2-cff8-11e5-80e4-4de65f51d7db.png)
![kontainerbefore](https://cloud.githubusercontent.com/assets/15268792/12946909/01531578-cff8-11e5-877c-cb051cd3fbcb.png)
