### ISSUE TITLE
FTT_DuctedFan_lg.cfg - Node points to wrong direction

### ISSUE THREAD

**Issue by RealKolago** [BobPalmer/FTT#127]
In FTT_DuctedFan_lg.cfg the Node points to wrong direction

Wrong:
node_stack_top = 0, 0, -3.63, 0, 0, 1, 3

Right:
node_stack_top = 0, 0, -3.63, 0, 0, -1, 3

**Comment by BobPalmer** [comment]
Fixed in a prior release
