### ISSUE TITLE
Honeybadger VTOL Atmospheric Engine

### ISSUE THREAD

**Issue by OakTree42** [BobPalmer/FTT#129]
This part has a weight of 3.75 t and a thrust of 15.0 kN...
I tied 32 of them together with minimal parts around them and they couldn't get above 0.3 TWR on Kerbin. Think they need to be adjusted a tad, either weight reduction or thrust increase or both.

**Comment by redelman** [comment]
This is still a problem with v 0.5.3.0

**Comment by BobPalmer** [comment]
Fixed in a prior release
