### ISSUE TITLE
Honeybadger all ducted fan engines use almost no power

### ISSUE THREAD

**Issue by ChainiaC** [BobPalmer/FTT#136]
All three ducted fan engines, the VTOL, the large and the small use next to no EC. I can launch a vessel with no power generation whatsoever and run multiple engines with only a couple of EC used after minutes of flight.

**Comment by sh1pman** [comment]
Just checked, still an issue. The EC consumption needs to be scaled up by at least two orders of magnitude.

**Comment by BobPalmer** [comment]
Fixed next patch
