### ISSUE TITLE
Contents labeling is wrong for LFO in round Kontainer

### ISSUE THREAD

**Issue by puetzk** [BobPalmer/FTT#151]
Specifically, UmbraSpaceIndustries/Kontainers/Assets/Tank_00.dds (supposed to be LFO?) is identical to Tank_09.dds. So when you configure the tank for LFO, the textures label it as Argon.

The previous version from 64def64de7025f942a250889db18cc0c8c434ccd seems to be correct..

Crinkle.dds and Crinkle_gold.dds are also identical files, but I don't see any problem from that (not sure if they were supposed to be different or not...)

**Comment by BobPalmer** [comment]
Fixed next release
