### ISSUE TITLE
unable to L click containers 1.2.2

### ISSUE THREAD

**Issue by entity775** [BobPalmer/FTT#160]
Hi bob seems i can't left click any containers to change resource contents since the latest update

**Comment by BobPalmer** [comment]
Probably a mod conflict of some kind?  I've been using these just fine?  Need more details, best bet is to post info on the forums.

**Comment by entity775** [comment]
Thanks
I think i will convert back to stock and add mods 1 at a time see where the conflict is  I don't know how i could have a problem though I am running all up to date mods   got rid of all 1.2.1

Thanks for responding so fastI let you know what i find out 

    On Wednesday, December 28, 2016 5:49 AM, Bob Palmer <notifications@github.com> wrote:
 

 Probably a mod conflict of some kind? I've been using these just fine? Need more details, best bet is to post info on the forums.—

**Comment by entity775** [comment]
O ye curious question are you going to be updating caribou to 1.2.2?
Thanks Josh 

    On Wednesday, December 28, 2016 7:12 AM, Joshua Nassau <joshua.nassau@yahoo.com> wrote:
 

 Thanks
I think i will convert back to stock and add mods 1 at a time see where the conflict is  I don't know how i could have a problem though I am running all up to date mods   got rid of all 1.2.1

Thanks for responding so fastI let you know what i find out 

    On Wednesday, December 28, 2016 5:49 AM, Bob Palmer <notifications@github.com> wrote:
 

 Probably a mod conflict of some kind? I've been using these just fine? Need more details, best bet is to post info on the forums.—
