### ISSUE TITLE
Career: Emptying a pre-filled Kontainer in the VAB leads to negative vessel value: launch and profit

### ISSUE THREAD

**Issue by Anbalsilfer** [BobPalmer/FTT#53]
Title pretty much says it all, but:

When adding Kontainers (and probably some of the other tank types as well, like the Honeybadgers) to a vessel in the VAB or SPH they are filled to capacity by default. If you manually empty them out before launch, however (such as in the use case of creating a logistic ship, which I assume FTT is for), the game seems to dramatically overestimate the value of the subtracted resources, causing the total vessel cost to become much lower than it should, and frequently ending up in the negative range.

**Comment by Anbalsilfer** [comment]
Just noticed this is probably more or less a duplicate of Issue #52, although not quite. As I pointed out, the problem doesn't just affect the Honeybadger parts.

**Comment by BobPalmer** [comment]
Should be fixed in next patch
