### ISSUE TITLE
Add a KAS option for FTT Kontainers

### ISSUE THREAD

**Issue by spaceparrot** [BobPalmer/FTT#61]
Could an option be added to have the different Kontainers be KAS storage? I'm sure there's a way to do that since Angel-125's MCM mod has a storage module that does something similar.

That's going to be a ton of storage, but it'd be fun to ship huge amounts of rover parts, science sensors, and other KAS-storable items from both KAS and KAS-friendly mods to colonies or stations. It'd also be aesthetically pleasing to have a huge Kontainer (or twelve) sitting near a Kolony, sending Kerbals out to grab stuff as needed for exploration, spare parts, etc.

**Comment by pectus-solentis** [comment]
You can say that again. And, what about the regular HB Cargo Pod having 80u of KAS (240u for jumbo pod) even if they are setted to ship freights?

**Comment by smjjames** [comment]
+1 to this idea as well.

**Comment by K-re** [comment]
I also agree with this Idea. However, it should probably wait until KAS and KIS become fully merged before being undertaken.

**Comment by Bear67** [comment]
Have you checked out the KIS mod that makes the small KAS/KIS parts in the field?
https://github.com/obivandamme/Workshop
