### ISSUE TITLE
New Part Request (Enclosed Adaptor)

### ISSUE THREAD

**Issue by CyberBlade007** [BobPalmer/FTT#62]
Hey RoverDude, Posting this on github as you asked. 

I am using MKS, FTT and a few other mods of yours to build a base. I like to use the large docking ports to connect my base together instead of the inflatable tubes. I was wondering if you could make a new adaptor similar to your FTT 3-2 adaptor. I would like it to be either enclosed or maybe you could build a tube through the center (similar to how I did it in the picture). The way I did it was by allowing parts to clip into each other, but once I had a few of these set up my game began to crash fairly often. 

![2015-01-15_00002](https://cloud.githubusercontent.com/assets/10859475/6054477/7e977ff8-aca2-11e4-94b2-2ee41ae1ea6b.jpg)

**Comment by pectus-solentis** [comment]
Agree. I hope that too.
