### ISSUE TITLE
Large Cargo Rack wont attach

### ISSUE THREAD

**Issue by john73738** [BobPalmer/FTT#80]
I have run into an issue where the large cargo rack will not attach on the stack attachment nodes, and one side of the "lateral" attachment nodes do not work as well. I have recreated this in two installs on two different computers.

**Comment by rasta013** [comment]
I've confirmed the same thing.  All three left side lateral nodes (in SPH) are not attaching to the Starlifter Cargo Adapter.  Right side works properly and it is possible to connect to the interior of the left side lateral with the adapter inverted as if to attach to the right lateral.  Tested this on my career and a clean install+USI Mod Catalog only. Screenshot showing inverted attachment on left lateral nodes.
![2015-05-07_00006](https://cloud.githubusercontent.com/assets/12317827/7530227/621a2ca8-f50a-11e4-8b6d-7931e07e3204.jpg)
