### ISSUE TITLE
honeybadger atmospheric vtol engines overheating in hover mode

### ISSUE THREAD

**Issue by zajc3w** [BobPalmer/FTT#82]
as in title.
To reproduce build any craft with honeybadger atmospheric vtol engines
activate hover mode
activate engines 
throttle up to takeoff
watch them explode after couple seconds due to overheating

**Comment by smjjames** [comment]
This also happens with the large ducted fans and ALMOST does with the medium ones. They get extremely hot at the same time either of the other two do, but the others explode before the medium ones manage to explode.

**Comment by Falkvinge** [comment]
This happens in regular hover mode, too. I just built a Honeybadger that didn't even make it from KSC to Runway Island before the VTOL engines exploded from overheating. Something in the new thermal model?
