### ISSUE TITLE
Part crash tolerance and heat resistance is extremely inconsistant with stock parts.

### ISSUE THREAD

**Issue by Marcafk** [BobPalmer/FTT#84]
I noticed a fuel tank failing to explode after a massive crash. Digging around in the files shows that the values are very far off 1.0 stock values.
Spherical hydrogen tank has crashTolerance = 45 and maxTemp = 3400 ,
Stock tanks, for instance FL-T400 has crashTolerance = 6 and maxTemp = 2000
Stock tanks also have the values breakingForce = 50 and breakingTorque = 50, I'm unsure what effect this has on durability, but the FTT tanks do seem to be far too durable.
I should point out that the Command 375 and control 375 are almost correct, as stock command modules do have a crashtolerance of 45, but their heat resistance is between 2000 and 2400 (or less for probe cores).

**Comment by Marcafk** [comment]
Further analysis shows that stock tanks and engines all have different values for breaking force and torque, also many components don't have these values, I believe the lack of this is what made a recent rocket with a large SAs module wobbly at that part.

**Comment by futrtrubl** [comment]
breaking force and torque don't affect the rigidity of joints, just when they snap. Rigidity is determined by node size and maybe part mass I believe.
