### ISSUE TITLE
Flipped attachment nodes on the large Starlifter Cargo Rack

### ISSUE THREAD

**Issue by aleander** [BobPalmer/FTT#89]
As in title, the usual KSP 1.0 transition issue. The small SCR is fine, but the large one appears to have all the nodes flipped (both the ends and the side-mounting nodes attach "inwards").

**Comment by OakTree42** [comment]
My testing indicates that only one 'side' is wrong, and the other 3 are right. Just as a sub note

**Comment by chrissnave** [comment]
I edited the following section in FTT_Structural_500_05.cfg to fix this issue...

// --- node definitions ---
// definition format is Position X, Position Y, Position Z, Up X, Up Y, Up Z

node_stack_cargo_01 = .8, 0, 0, 1, 0, 0.0, 3
node_stack_cargo_02 = -.8, 0, 0, -1, 0, 0.0, 3
node_stack_cargo_03 = .8, 7.5, 0, 1, 0, 0.0, 3
node_stack_cargo_04 = -.8, 7.5, 0, -1, 0, 0.0, 3
node_stack_cargo_05 = .8, -7.5, 0, 1, 0, 0.0, 3
node_stack_cargo_06 = -.8, -7.5, 0, -1, 0, 0.0, 3


node_stack_bottom_R = 0, -11.25, 0, 0.0, -1.0, 0.0, 3
node_stack_top_L = 0, 11.25, 0, 0.0, 1.0, 0.0, 3

**Comment by henrybauer** [comment]
@chrissnave thanks that works perfectly for me.  Your patch also fixes the top and bottom nodes so you can attach it correctly

**Comment by chrissnave** [comment]
You're welcome. Yeah seemed like a few nodes were backwards, hope this gets fixed when FTT gets its overhaul. Love the Starlifter parts.
