### ISSUE TITLE
Kontainor 2.5 - Rocket Part tank costs.

### ISSUE THREAD

**Issue by Caithloki** [BobPalmer/FTT#91]
The tank says it costs 3800 funds and it does for most tanks (minus the negative cost issue) but with the rocket parts it cost over 4 million funds empty.

**Comment by Goldenpsp** [comment]
Seems like it can be an issue due to EPL's change in rocketparts cost vs CRP

**Comment by plague006** [comment]
Not sure if related, but MetallicOre 2.5m Kontainer has a negative cost (that is, you *get* money for using it)
