### ISSUE TITLE
Kontainers size/mass seems off?

### ISSUE THREAD

**Issue by OakTree42** [BobPalmer/FTT#97]
If you take for example the 1.25 FTT cargo container, and skin it for ore then compare it to the default container for Ore, you may notice that the 1.25 holds 2500 units of ore while the small holding tank that is stock holds 300 Ore, yet they are about the same size. In fact the 1.25 FTT cargo kontainer weighs 0.4 empty while the stock weighs 0.5 empty. This variation seems to hold across multiple materials so I think perhaps a multiplier is off in the projected storage amounts for the FTT cargo kontainers by comparison to the stock by almost an order of magnitude. (300 vs 2500)

**Comment by NyankoSensei** [comment]
sure something is off, Kontainers take value from volume and measure it in Lt, for the stock i don't know, if we watch the 2 sides for 1,25 mt tank 500kg are too much, i can understand a weight of 150-200 kg for 2-3 psi
